### ISSUE TITLE
Plugin Error with PhpStorm 2019.3

### ISSUE THREAD

**Issue by mems** [syuchan1005/NPMScriptRunner#1]
The plugin ~~doesn't work anymore and~~ got this error after upgrade PhpStorm 2019.2 to 2019.3:

```
Plugin Error
Plugin "NPM Script Runner" defines no module dependencies (supported only in IntelliJ IDEA).
```

I think it's related to this: [Plugin Compatibility with IntelliJ Platform Products / IntelliJ Platform SDK DevGuide](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html).

> If a plugin does not include any module dependency tags in its plugin.xml, it's assumed to be a legacy plugin and is loaded only in IntelliJ IDEA, so it may use classes from Java plugin.
> — [git.jetbrains.org - idea/community.git/blob - platform/core-impl/src/com/intellij/ide/plugins/PluginManagerCore.java](http://git.jetbrains.org/?p=idea/community.git;a=blob;f=platform/core-impl/src/com/intellij/ide/plugins/PluginManagerCore.java;hb=0b42a0b3ada5881f8c9e90d4b5ffbbee00aacd6b#l577)

**Comment by syuchan1005** [comment]
Thank you for reporting the problem.
However, this plugin is not currently being developed.

However, you may be able to resolve the reported problem in one of the following ways.

- Fixed deprecated AllIcons.java
- Sets the "until" version of this plugin to 193. *

I am waiting for your pull request.
